### PR TITLE
Revert to Base Code

### PR DESCRIPTION
**Pull request by Game-GameEdition**
For the season of 2023 we are required to start from scratch and make new code to use on the robot (no C+V from 2022!). This will be where we are starting from for programming the robot for the season of 2023. 

- Added motor controller dependencies. 
- Devoid of everything else.

### CODE REVIEW

**Comment by AidenHogan** [comment]
LGTM!!

**Comment by Game-GameEdition** [comment]
> LGTM!!

nerd!

**Review by AidenHogan — APPROVED** [review]
Good start w/ adding the motor controllers, looks good Victor.

**Comment by Game-GameEdition** [comment]
THank you soo much Aiden!1!1!1!1!

**Pull request merged**
